version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "tarunbatta"
    assignees:
      - "tarunbatta"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
