const js = require("@eslint/js");

module.exports = [
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: 2018,
      sourceType: "commonjs",
      globals: {
        console: "readonly",
        process: "readonly",
        Buffer: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        module: "readonly",
        require: "readonly",
        exports: "readonly",
        global: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Atomics: "readonly",
        SharedArrayBuffer: "readonly",
        document: "readonly",
      },
    },
    rules: {
      "eol-last": "off",
      indent: "off",
      "linebreak-style": "off",
      "max-len": "off",
      "new-cap": "off",
      "no-alert": "warn",
      "no-console": "off",
      "no-dupe-args": "error",
      "no-eq-null": "off",
      "no-fallthrough": "error",
      "no-floating-decimal": "off",
      "no-global-assign": "error",
      "no-multi-str": "off",
      "no-redeclare": "error",
      "no-sequences": "off",
      "no-unused-vars": "off",
      "no-useless-escape": "off",
      quotes: "off",
      "require-atomic-updates": "off",
      semi: "off",
      "space-before-function-paren": "off",
      "no-undef": "warn",
    },
  },
];
